//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kwresource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword
    {
        public string Id { get; set; }
        public string kw { get; set; }
        public Nullable<int> volume { get; set; }
        public string landingpage { get; set; }
        public Nullable<int> currentranking { get; set; }
        public Nullable<int> kd { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> newcost { get; set; }
        public string sessionid { get; set; }
        public Nullable<int> stt { get; set; }
        public string nosignkw { get; set; }
    }
}
